import type { StashCollection, StashItem, StashSettings } from './types';

const now = Date.now();
const ago = (hours: number) => now - hours * 60 * 60 * 1000;

export const sampleCollections: StashCollection[] = [
  { id: 'inspiration', name: 'Inspiration', icon: 'sparkles', color: '#27d8c4', createdAt: ago(240) },
  { id: 'work', name: 'Work', icon: 'briefcase', color: '#6ea8ff', createdAt: ago(220) },
  { id: 'recipes', name: 'Recipes', icon: 'leaf', color: '#7ed889', createdAt: ago(180) },
  { id: 'study', name: 'Study', icon: 'graduation', color: '#b18cff', createdAt: ago(150) },
];

export const sampleItems: StashItem[] = [
  {
    id: 'cabin',
    type: 'screenshot',
    title: 'Cabin design inspiration',
    description: 'Ideas for a modern, minimal cabin that blends into the landscape. Natural materials, large windows, and cozy interiors with a focus on light.',
    notes: 'Love the use of natural wood and the connection to surrounding nature. Save ideas for the living room layout and the deck materials.',
    url: 'https://www.dezeen.com/cabin-design-inspiration',
    tags: ['architecture', 'cabin', 'minimal', 'nature', 'ideas'],
    collectionId: 'inspiration',
    imageUrl: '/assets/cabin.jpg',
    imageCount: 3,
    source: 'Web Clipper',
    size: 3565158,
    createdAt: ago(0.02),
    updatedAt: ago(0.02),
    lastInteractedAt: ago(0.02),
    reminderAt: now + 24 * 60 * 60 * 1000,
    pinned: true,
    favorite: true,
    archived: false,
  },
  {
    id: 'tools',
    type: 'link',
    title: 'The best productivity tools in 2024',
    description: 'A curated collection of minimalist, local-first tools designed to stay out of your way and respect user privacy.',
    notes: 'Evaluate offline-first architecture principles.',
    url: 'https://notion.com',
    tags: ['tools', 'productivity', 'work'],
    collectionId: 'work',
    source: 'Safari Extension',
    createdAt: ago(0.08),
    updatedAt: ago(0.08),
    lastInteractedAt: ago(0.08),
    pinned: false,
    favorite: false,
    archived: false,
  },
  {
    id: 'feedback',
    type: 'note',
    title: 'Client feedback — Q2 notes',
    description: 'Clarify onboarding, reduce friction in search, and surface saved work sooner with deterministic scoring.',
    notes: 'Next review on Friday at 10am with engineering team.',
    tags: ['work', 'client', 'planning'],
    collectionId: 'work',
    size: 1228,
    createdAt: ago(0.3),
    updatedAt: ago(0.3),
    lastInteractedAt: ago(0.3),
    pinned: false,
    favorite: false,
    archived: false,
  },
  {
    id: 'contract',
    type: 'file',
    title: 'Contract_v2.pdf',
    description: 'Signed project agreement and current statement of work.',
    notes: 'Stored locally with secure sandboxed preview.',
    tags: ['documents', 'work'],
    collectionId: 'work',
    fileName: 'Contract_v2.pdf',
    mimeType: 'application/pdf',
    size: 245760,
    createdAt: ago(1),
    updatedAt: ago(1),
    lastInteractedAt: ago(1),
    pinned: false,
    favorite: true,
    archived: false,
  },
  {
    id: 'skincare',
    type: 'image',
    title: 'Skincare brand ideas',
    description: 'Amber glass apothecary bottles, tactile travertine stone pedestals, clean typography, and warm lighting.',
    notes: 'Inspiration for sustainable packaging materials and label layouts.',
    tags: ['branding', 'packaging', 'inspiration'],
    collectionId: 'inspiration',
    imageUrl: '/assets/skincare.jpg',
    size: 2202009,
    createdAt: ago(2),
    updatedAt: ago(2),
    lastInteractedAt: ago(2),
    pinned: false,
    favorite: false,
    archived: false,
  },
  {
    id: 'tokyo',
    type: 'link',
    title: 'Tokyo travel guide',
    description: 'Quiet kissaten coffee bars, Yanaka historic alleys, contemporary galleries in Kiyosumi, and sunset viewpoints.',
    notes: 'Focus on Yanaka and Kiyosumi-Shirakawa architecture walks.',
    url: 'https://lonelyplanet.com/japan/tokyo',
    tags: ['travel', 'tokyo', 'inspiration'],
    collectionId: 'inspiration',
    imageUrl: '/assets/tokyo.jpg',
    source: 'Chrome Share',
    createdAt: ago(3),
    updatedAt: ago(3),
    lastInteractedAt: ago(3),
    pinned: false,
    favorite: true,
    archived: false,
  },
  {
    id: 'meeting',
    type: 'note',
    title: 'Meeting notes — May 12',
    description: 'Launch checklist, accessibility color contrast compliance, and offline PWA service worker caching verification.',
    notes: 'Verify responsive touch targets and safe area inset support.',
    tags: ['meeting', 'work'],
    collectionId: 'work',
    createdAt: ago(5),
    updatedAt: ago(5),
    lastInteractedAt: ago(5),
    pinned: false,
    favorite: false,
    archived: false,
  },
  {
    id: 'porto',
    type: 'link',
    title: 'Porto, Portugal – Travel Guide',
    description: 'Historic Ribeira waterfront along the Douro river, Dom Luis I bridge, azulejo ceramic tiles, and seaside trams.',
    notes: '✓ Things to do\n✓ Food & Drinks\n✓ Where to stay',
    url: 'https://visitporto.travel',
    tags: ['travel', 'guide', 'places'],
    collectionId: 'inspiration',
    imageUrl: '/assets/porto.jpg',
    source: 'Web Clipper',
    createdAt: ago(0.01),
    updatedAt: ago(0.01),
    lastInteractedAt: ago(0.01),
    pinned: false,
    favorite: false,
    archived: false,
  },
  {
    id: 'chair',
    type: 'product',
    title: 'Teak lounge chair',
    description: 'A sculptural outdoor Danish modern lounge chair crafted in solid oiled plantation teak with weatherproof woven cord.',
    notes: 'Compare dimensions with balcony floor plan.',
    url: 'https://nordiccraft.com/teak-chair',
    tags: ['furniture', 'outdoor', 'inspiration'],
    collectionId: 'inspiration',
    imageUrl: '/assets/teak_chair.jpg',
    source: 'Product bookmark',
    createdAt: ago(24 * 8),
    updatedAt: ago(24 * 8),
    lastInteractedAt: ago(24 * 8),
    lastResurfacedAt: ago(24 * 6),
    pinned: false,
    favorite: true,
    archived: false,
  },
  {
    id: 'quote-eames',
    type: 'idea',
    title: '“The details are not the details. They make the design.”',
    description: 'Charles Eames on intentional craft, deliberate material choices, and fluid user experience.',
    notes: 'Guiding principle for every UI transition and tactile interaction.',
    tags: ['design', 'quotes', 'ideas'],
    collectionId: 'inspiration',
    source: 'Thought capture',
    createdAt: ago(24 * 7),
    updatedAt: ago(24 * 7),
    lastInteractedAt: ago(24 * 7),
    pinned: false,
    favorite: false,
    archived: false,
  },
  {
    id: 'kitchen',
    type: 'note',
    title: 'Kitchen renovation ideas',
    description: 'Fluted white oak island with honed Calacatta marble counters and concealed integrated appliances.',
    notes: 'Check lead time on brushed nickel tapware and under-cabinet LED strips.',
    tags: ['home', 'renovation', 'ideas'],
    collectionId: 'inspiration',
    imageUrl: '/assets/cabin.jpg',
    createdAt: ago(0.15),
    updatedAt: ago(0.15),
    lastInteractedAt: ago(0.15),
    pinned: false,
    favorite: false,
    archived: false,
  },
  {
    id: 'matcha',
    type: 'product',
    title: 'Matcha green tea cleanser',
    description: 'Gentle clarifying face wash formulated with ceremonial grade Uji matcha and fermented rice extract.',
    notes: 'Clean skincare routine.',
    url: 'https://cleanbeauty.jp/matcha',
    tags: ['skincare', 'product', 'inspiration'],
    collectionId: 'inspiration',
    imageUrl: '/assets/skincare.jpg',
    createdAt: ago(24 * 3),
    updatedAt: ago(24 * 3),
    lastInteractedAt: ago(24 * 3),
    pinned: false,
    favorite: true,
    archived: false,
  },
  {
    id: 'bread',
    type: 'link',
    title: 'No-knead focaccia',
    description: 'Reliable overnight fermentation method with rosemary, flaky sea salt, and a crisp golden olive-oil crust.',
    notes: 'Use 80% hydration and cold proof for 24 hours.',
    url: 'https://bakingjournal.com/focaccia',
    tags: ['recipes', 'baking'],
    collectionId: 'recipes',
    createdAt: ago(24 * 20),
    updatedAt: ago(24 * 20),
    lastInteractedAt: ago(24 * 18),
    pinned: false,
    favorite: false,
    archived: false,
  },
];

export const defaultSettings: StashSettings = {
  id: 'settings',
  theme: 'dark',
  accent: 'jade',
  onboardingComplete: false,
};
